main/announcements/views.py
""" Module for Announcement Views """
import datetime

from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for

from main import forms
from main.auth import models
from main.announcements import models
from main.auth import decorators


bp = Blueprint('announcements', __name__)


@bp.route('/announcements/create', methods=('GET','POST'))
@decorators.permission_TA
def announcements_create():
    """ View creating Announcements. """
    form = forms.formula_create(
                    table='announcement',
                    subject='String',
                    body='TextArea' )

    if form.validate_on_submit():
        announcement = models.Announcement(
                            subject=form.subject.data,
                            body=form.body.data,
                            created_text=datetime.datetime.now().astimezone().strftime('%d %b %Y at %H:%M %Z'),
                            author_id=g.user['id'] )
        announcement.save()

        flash('Announcement successfully posted')
        return redirect(url_for('index'))
    
    else:
        form.outtakes()

    return render_template('announcements/create.html', form=form)
                                                                ### END Announcement: Create


@bp.route('/announcements/<int:id>/update', methods=('GET', 'POST'))
@decorators.permission_TA
def announcements_update(id):
    """ View for updating Announcements. """
    announcement = models.Announcement.query.filter_by(id=id).first()

    form = forms.formula_update(
                    table='announcement',
                    subject=('String',announcement.subject),
                    body=('TextArea',announcement.body) )

    if form.validate_on_submit():        
        announcement.update(
            subject=form.subject.data,
            body=form.body.data,
            updated_text=datetime.datetime.now().astimezone().strftime('%d %b %Y at %H:%M %Z') )

        flash('Announcement successfully updated')
        return redirect(url_for('index'))

    else:
        form.outtakes()

    return render_template('announcements/update.html', announcement=announcement, form=form)
                                                                ### END Announcement: Update


@bp.route('/announcements/<int:id>/delete', methods=('POST',))
@decorators.permission_TA
def announcements_delete(id):
    """ View for deleting Announcements. """
    announcement = models.Announcement.query.filter_by(id=id).first()
    announcement.delete()

    flash('Announcement successfully deleted')
    return redirect(url_for('index'))
                                                                ### END Announcement: Delete

main/views.py
### CourseWebApp.view.index
import datetime
import functools
import os

from flask import Blueprint
from flask import flash
from flask import g
from flask import redirect
from flask import render_template
from flask import request
from flask import session
from flask import url_for
from werkzeug.exceptions import abort

from main import database
from main import forms
from main import models
from main.auth import decorators


bp = Blueprint('index', __name__)


@bp.route('/')
@decorators.permission_everyone
def index():
    """ View for main.index """
    welcomes_proto = models.Model( table='welcome' )
    welcomes = welcomes_proto.db_select(
                    limit='1',
                    all=True )

    announcements_proto = models.Model( table='announcement' )
    announcements = announcements_proto.db_select(
                        join=True,
                        order='created DESC',
                        all=True )

    announcements_size = len(announcements)

    return render_template('index/index.html', welcomes=welcomes, announcements=announcements, announcements_size=announcements_size)
                                                                ### END Index


@bp.route('/welcome', methods=('GET', 'POST'))
@decorators.permission_professor
def welcome_create():
    """ View for creating Welcome greeting. """
    welcome = models.Model( table='welcome' )

    form = forms.formula_create(
                    table='welcome',
                    greeting='CKEditor' )

    if form.validate_on_submit():
        form.formContent['author_id'] = g.user['id']
        form.formulateContent()

        welcome.__dict__ = form.formContent
        welcome.db_insert()

        flash('Welcome greeting created')
        return redirect(url_for('index'))

    else:
        form.outtakes()

    return render_template('index/welcome.html', welcome=welcome, form=form)
                                                                ### END Welcome: Create


@bp.route('/welcome/update', methods=('GET', 'POST'))
@decorators.permission_professor
def welcome_update():
    """ For updating Welcome greeting. """
    welcome = models.Model( table='welcome' )
    welcome.db_select( where={'id': 1} )

    form = forms.formula_update( 
                table='welcome',
                greeting=('CKEditor',welcome.greeting) )
    form.formContent = welcome.__dict__
    
    if form.validate_on_submit():
        form.formulateContent()

        welcome.__dict__ = form.formContent
        welcome.db_update(1)

        flash("Welcome greeting updated")
        return redirect(url_for('index'))

    else:
        form.outtakes()

    return render_template('index/update.html', welcome=welcome, form=form)
                                                                ### END Welcome: Update

main/templates/index/index.html
{% extends 'base.html' %}

<script src="https://cdn.ckeditor.com/4.10.0/standard/ckeditor.js"></script>
 {{ ckeditor.load() }}

<!-- BLOCK: WELCOME -->
{% block welcome %}
	<div>
		<br>
		{% if g.user['role_id'] == 4 %}
			<a class="action" href="{{ url_for('index.welcome_create') }}">Create</a>
			<a class="action" href="{{ url_for('index.welcome_update') }}">Edit</a>
		{% endif %}
	</div>
  		<div class="welcomeContainer">
  		{% for welcome in welcomes %}
			<div class="welcome">{{ welcome['greeting']|safe }}</div>
  		{% endfor %}
		</div>
	
		<hr>
{% endblock %}


<!-- BLOCK: HEADER -->
{% block header %}
	<h1 style="font-size: 300%;">{% block title %}Announcements{% endblock %}</h1>
 	{% if g.user and g.user['role_id'] > 2 %}
		<a class="action" href="{{ url_for('announcements.announcements_create') }}">New</a>
  	{% endif %}
{% endblock %}


<!-- BLOCK: CONTENT -->
{% block content %}
	<script type=text/javascript>
		// For Announcements click-behavior
		var announcements_size = {{ announcements_size|tojson|safe }};
	
		for (let i = 0; i < announcements_size; i++) {
	  		$(document).ready(
				function() {
		  			$('[name="announcement_divContainer[' + i + ']"]').click(
			  			function() {
							$('[name="announcement_p[' + i + ']"]').slideToggle();
						});
		  			});
			}

		// For displaying latest Announcement as default
	  	$(document).ready(function() {
			$('[name="announcement_p[0]"]').show(); });
	</script>
  	{% set ns = namespace(i = 0) %}
  	{% for announcement in announcements %}
		{% set announcement_divContainer = 'announcement_divContainer[{0}]'.format(ns.i) %}
		{% set announcement_p = 'announcement_p[{0}]'.format(ns.i) %}
		<article class="post">
	  		<header>
				<div>
					<div class="announcement_divContainer" name="{{ announcement_divContainer }}">
						<div class="announcement_div">
		  					<h1>{{ announcement['subject'] }}</h1>
		  					{% if announcement['updated_text'] %}
								<div class="about">by {{ announcement.users['username'] }}.
			  						<b>Created:</b> {{ announcement['created_text'] }},
			  						<b>Updated:</b> {{ announcement['updated_text'] }}.
								</div>
		  					{% else %}
								<div class="about">by {{ announcement.users['username'] }}.
			  						<b>Created:</b> {{ announcement['created_text'] }}.
								</div>
		  					{% endif %}
						</div>
					</div>
				</div>
				{% if g.user and g.user['role_id'] > 2 %}
		  			<a class="action" href="{{ url_for( 'announcements.announcements_update', id=announcement['id'] ) }}">Edit</a>
				{% endif %}
	  		</header>
	  		<!-- Tried using CKEditor for Announcements too
	  			 But JSON breaks the editor.  E.g., Marking the announcement posts as
	  			 safe via "post|tojson|safe" breaks CKEditor's text. -->
	  		<p class="announcement_p" name={{announcement_p}}>{{ announcement['body'] }}</p>
		</article>
		{% set ns.i = ns.i + 1 %}
		{% if not loop.last %}
	  		<hr>
		{% endif %}
  	{% endfor %}
  	<hr>
{% endblock %}

main/templates/index/update.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Edit Welcome{% endblock %}</h1>
{% endblock %}

{% block content %}
    <form method="post">
        {{ form.csrf_token() }}

        {% for field in form if (field.name != 'csrf_token') and (field.name != 'submit') %}
            {{ field.label }}
            {{ field }}
        {% endfor %}

        <hr>

        {{ form.submit() }}
        <a href="{{ url_for('index') }}"><button type="button">Back to Main Page</button></a>
    </form>
    {{ ckeditor.load() }}
    {{ ckeditor.config(name='greeting') }}
{% endblock %}

main/templates/index/welcome.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Welcome!{% endblock %}</h1>
{% endblock %}

{% block content %}
    <form method="post">
        {{ form.csrf_token() }}

        {% for field in form if (field.name != 'csrf_token') and (field.name != 'submit') %}
            {{ field.label }}
            {{ field }}
        {% endfor %}

        <hr>

        {{ form.submit() }}
        <a href="{{ url_for('index') }}"><button type="button">Back to Main Page</button></a>
    </form>
    {{ ckeditor.load() }}
    {{ ckeditor.config(name='greeting') }}
{% endblock %}