main/announcements/models.py
""" Module for Announcement Models """
import datetime

import sqlalchemy as db
from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy.orm import relationship
from werkzeug.security import check_password_hash, generate_password_hash

from main.database import Base, db_session
from main.models import Basic, Model


Column = db.Column


class Announcement(Model):

    __table_args__ = {'extend_existing': True}

    id = Column(db.Integer, primary_key=True)
    subject = Column(db.Text, nullable=False)
    body = Column(db.Text, nullable=False)
    created = Column(db.DateTime, nullable=False, default=db.func.current_timestamp())
    created_text = Column(db.Text, nullable=False)
    updated_text = Column(db.Text, nullable=True)
    author_id = Column(db.Integer, db.ForeignKey("user.id"), nullable=False)

    #### Relationships
    users = relationship("main.auth.models.User", back_populates="announcements")

    def __repr__(self):
    	return f"Announcement: {self.subject}"

main/announcements/__init__.py
### CourseWebApp.announcements

""" For module 'main.announcements' """

from flask import Blueprint

from main.announcements import views

main/announcements/views.py
""" Module for Announcement Views """
import datetime

from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for

from main import forms
from main.auth import models
from main.announcements import models
from main.auth import decorators


bp = Blueprint('announcements', __name__)


@bp.route('/announcements/create', methods=('GET','POST'))
@decorators.permission_TA
def announcements_create():
    """ View creating Announcements. """
    form = forms.formula_create(
                    table='announcement',
                    subject='String',
                    body='TextArea' )

    if form.validate_on_submit():
        announcement = models.Announcement(
                            subject=form.subject.data,
                            body=form.body.data,
                            created_text=datetime.datetime.now().astimezone().strftime('%d %b %Y at %H:%M %Z'),
                            author_id=g.user['id'] )
        announcement.save()

        flash('Announcement successfully posted')
        return redirect(url_for('index'))
    
    else:
        form.outtakes()

    return render_template('announcements/create.html', form=form)
                                                                ### END Announcement: Create


@bp.route('/announcements/<int:id>/update', methods=('GET', 'POST'))
@decorators.permission_TA
def announcements_update(id):
    """ View for updating Announcements. """
    announcement = models.Announcement.query.filter_by(id=id).first()

    form = forms.formula_update(
                    table='announcement',
                    subject=('String',announcement.subject),
                    body=('TextArea',announcement.body) )

    if form.validate_on_submit():        
        announcement.update(
            subject=form.subject.data,
            body=form.body.data,
            updated_text=datetime.datetime.now().astimezone().strftime('%d %b %Y at %H:%M %Z') )

        flash('Announcement successfully updated')
        return redirect(url_for('index'))

    else:
        form.outtakes()

    return render_template('announcements/update.html', announcement=announcement, form=form)
                                                                ### END Announcement: Update


@bp.route('/announcements/<int:id>/delete', methods=('POST',))
@decorators.permission_TA
def announcements_delete(id):
    """ View for deleting Announcements. """
    announcement = models.Announcement.query.filter_by(id=id).first()
    announcement.delete()

    flash('Announcement successfully deleted')
    return redirect(url_for('index'))
                                                                ### END Announcement: Delete

main/templates/announcements/create.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}New Announcement{% endblock %}</h1>
{% endblock %}

{% block content %}
    <form method="post">
        {{ form.csrf_token() }}

        {% for field in form if (field.name != 'csrf_token') and (field.name != 'submit') %}
            {{ field.label }}
            {{ field }}
        {% endfor %}

        <hr>
        {{ form.submit() }}
        <a href="{{ url_for('index') }}"><button type="button">Back to Main Page</button></a>
    </form>
{% endblock %}

main/templates/announcements/update.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Edit "{{ announcement['subject'] }}"{% endblock %}</h1>
{% endblock %}

{% block content %}
    <form method="post">
        {{ form.csrf_token() }}

        {% for field in form if (field.name != 'csrf_token') and (field.name != 'submit') %}
            {{ field.label }}
            {{ field }}
        {% endfor %}

        <hr>

        {{ form.submit() }}
        
        <a href="{{url_for('index')}}"><button type="button">Back to Main Page</button></a>
    </form>
    <hr>
    <form action="{{ url_for('announcements.announcements_delete', id=announcement['id']) }}" method="post">
        <input class="danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
    </form>
{% endblock %}