main/homework/models.py
""" Module for Homework Models """
import datetime

import sqlalchemy as db
from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy.orm import relationship
from werkzeug.security import check_password_hash, generate_password_hash

from main.database import Base, db_session
from main.models import Basic, Model


Column = db.Column


class Homework(Model):
    __table_args__ = {'extend_existing': True}

    id = Column(db.Integer, primary_key=True)
    Zahl = Column(db.Integer, nullable=False)
    due = Column(db.String(32), nullable=False)
    title = Column(db.String(128), nullable=False)
    keywords = Column(db.Text, nullable=False)
    file_homework = Column(db.Text)
    created = Column(db.DateTime, nullable=False, default=datetime.datetime.now().astimezone())
    author_id = Column(db.Integer, db.ForeignKey("user.id"), nullable=False)

    #### Relationships
    users = relationship("main.auth.models.User", back_populates="homeworks")

    def __repr__(self):
        return f"Homework: {self.Zahl}"

main/homework/__init__.py
### CourseWebApp.homework

""" For module 'main.homework' """

from main.homework import views

main/homework/views.py
""" Module for Homework Views """
from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for

from main import forms, uploads
from main.auth import decorators
from main.auth.models import User
from main.database import db_session
from main.homework import models


bp = Blueprint('homework', __name__)


@bp.route('/homework')
@decorators.permission_everyone
def homework_index():
    """ View for Homework index """
    homeworks = models.Homework.query.join(User).all()

    return render_template('homework/homework.html', homeworks=homeworks)
                                                                ### END Homework Index


@bp.route('/homework/create', methods=('GET','POST'))
@decorators.permission_professor
def homework_create():
    """ View for creating Homework """
    form = forms.formula_create(
                        table='homework',
                        Zahl='Integer',
                        due='String',
                        title='String',
                        keywords='String',
                        file_homework='File' )

    if form.validate_on_submit():
        filename = uploads.upload(form.file_homework.data, 'homework')

        homework = models.Homework(
            id=form.Zahl.data,
            Zahl=form.Zahl.data,
            due=form.due.data,
            title=form.title.data,
            keywords=form.keywords.data,
            file_homework=filename,
            author_id=g.user['id'] )
        homework.save()

        flash(f"Homework {form.Zahl.data} successfully created")
        return redirect(url_for('homework.homework_index'))

    else:
        form.outtakes()

    return render_template('homework/create.html', form=form)
                                                                ### END Homework: Create


@bp.route('/homework/<int:id>/update', methods=('GET', 'POST'))
@decorators.permission_TA
def homework_update(id):
    """ View for updating Homework """
    homework = models.Homework.query.filter_by(id=id).first()

    form = forms.formula_update(
                    table='homework',
                    id=id,
                    Zahl=('Integer',homework.Zahl),
                    due=('String',homework.due),
                    title=('String',homework.title),
                    keywords=('String',homework.keywords),
                    file_homework=('File',None) )

    if form.validate_on_submit():
        filename = uploads.upload(form.file_homework.data, 'homework')
        homework.update(
            id=form.Zahl.data,
            Zahl=form.Zahl.data,
            due=form.due.data,
            title=form.title.data,
            keywords=form.keywords.data,
            file_homework=filename )

        flash(f"Homework {id} successfully updated")
        return redirect(url_for('homework.homework_index'))

    else:
        form.outtakes()

    return render_template('homework/update.html', homework=homework, form=form)
                                                                ### END Homework: Update


@bp.route('/homework/<int:id>/delete', methods=('POST',))
@decorators.permission_professor
def homework_delete(id):
    """ View for deleting Homework """
    homework = models.Homework.query.filter_by(id=id).first()
    homework.delete()

    flash(f"Homework {id} successfully deleted")
    return redirect(url_for('homework.homework_index'))
                                                                ### END Homework: Delete

main/templates/homework/create.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}New Homework Assignment{% endblock %}</h1>
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {{ form.csrf_token() }}

        {% for field in form if (field.name != 'csrf_token') and (field.name != 'submit') %}
            {% if field.name == 'Zahl' %}
                {{ field.label(text='Assignment No.') }}
                {{ field }}
            {% elif field.name == 'file_homework' %}
                {{ field.label(text='File') }}
                {{ field }}
            {% else %}
                {{ field.label }}
                {{ field }}
            {% endif %}
        {% endfor %}

        <hr>

        {{ form.submit() }}
        <a><button type="button" onClick = "this.form.reset()">Reset</button></a>
        <hr><hr>
        <a href="{{ url_for('homework.homework_index') }}"><button type="button">Back to Homework</button></a>
    </form>
{% endblock %}

main/templates/homework/homework.html
{% extends 'base.html' %}

{% block header %}
	<h1>{% block title %}Homework{% endblock %}</h1>
	{% if g.user['role_id'] == 4 %}
		<a class="action" href="{{ url_for('homework.homework_create') }}">New Assignment</a>
	{% endif %}
{% endblock %}

{% block content %}
	{% for homework in homeworks %}
		<article class="post">
			<header class="homework_post">
				<div class="homework_postContainer">
					<div class="homework_post">
						<h1>Homework {{ homework['id'] }}: <a href="/gg">{{ homework['title'] }}</a></h1>
						<span style="color: slategray; font-weight: bold; font-size: 110%;">Due: {{ homework['due'] }}</span>
						<div class="about">Keywords: {{ homework['keywords'] }}</div>
					</div>
				</div>
				{% if g.user and g.user['role_id'] > 2 %}
					<a class="action" href="{{ url_for('homework.homework_update', id=homework['id'] ) }}">Edit</a>
				{% endif %}
			</header>
		</article>
	{% endfor %}
{% endblock %}

main/templates/homework/update.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Edit "{{ homework['title'] }}"{% endblock %}</h1>
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {{ form.csrf_token() }}
        
        {% for field in form if (field.name != 'csrf_token') and (field.name != 'submit') %}
            {% if field.name == 'Zahl' %}
                {{ field.label(text='Assignment No.') }}
                {{ field }}
            {% elif field.name == 'file_homework' %}
                {{ field.label(text='File') }}
                {{ field }}
            {% else %}
                {{ field.label }}
                {{ field }}
            {% endif %}
        {% endfor %}

        <hr>

        {{ form.submit() }}
        <a href="{{ url_for('homework.homework_index') }}"><button type="button">Back to Homework</button></a>
    </form>
    <br>
    <form action="{{ url_for('homework.homework_delete', id=homework['Zahl']) }}" method="post">
        <input class="danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
    </form>
{% endblock %}