main/lectures/models.py
""" Module for Lecture Models """
import datetime

import sqlalchemy as db
from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy.orm import relationship
from werkzeug.security import check_password_hash, generate_password_hash

from main.database import Base, db_session
from main.models import Basic, Model


Column = db.Column


class Lecture(Model):
    __table_args__ = {'extend_existing': True}

    id = Column(db.Integer, primary_key=True)
    Zahl = Column(db.Integer, nullable=False)
    week = Column(db.Integer, nullable=False)
    day = Column(db.String(32), nullable=False)
    title = Column(db.String(64), nullable=False)
    summary = Column(db.Text, nullable=False)
    file_lecture = Column(db.Text)
    created = Column(db.DateTime, nullable=False, default=datetime.datetime.now().astimezone())
    author_id = Column(db.Integer, db.ForeignKey("user.id"), nullable=False)

    #### Relationships
    users = relationship("main.auth.models.User", back_populates="lectures")

    def __repr__(self):
        return f"Lecture: {self.Zahl}"

main/lectures/__init__.py
### CourseWebApp.lectures

""" For module 'main.lectures' """

from main.lectures import views

main/lectures/views.py
""" Module for Lecture Views """
from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for

from main import forms, uploads
from main.auth import decorators
from main.auth.models import User
from main.database import db_session
from main.lectures import models


bp = Blueprint('lectures', __name__)


@bp.route('/lectures')
@decorators.permission_everyone
def lectures_index():
    """ View for Lectures index """
    lectures = models.Lecture.query.join(User).all()

    ### Gadget for webpage aesthetic.
    ### See BLOCK: CONTENT in lectures.html
    try:
        M = max([lecture.week for lecture in lectures])
    except:
        M = 0

    return render_template('lectures/lectures.html', lectures=lectures, M=M)
                                                                ### END Lectures Index


@bp.route('/lectures/create', methods=('GET','POST'))
@decorators.permission_professor
def lectures_create():
    """ View for creating Lectures """
    form = forms.formula_create(
                    table='lecture',
                    week='Integer',
                    Zahl='Integer',
                    day='String',
                    title='String',
                    summary='TextArea',
                    file_lecture='File' )

    if form.validate_on_submit():
        filename = uploads.upload(form.file_lecture.data, 'lectures')
        lecture = models.Lecture(
            id=form.Zahl.data,
            Zahl=form.Zahl.data,
            week=form.week.data,
            day=form.day.data,
            title=form.title.data,
            summary=form.summary.data,
            file_lecture=filename,
            author_id=g.user['id'] )
        lecture.save()

        flash(f"Lecture {form.Zahl.data} successfully created")
        return redirect(url_for('lectures.lectures_index'))

    else:
        form.outtakes()

    return render_template('lectures/create.html', form=form)
                                                                ### END Lectures: Create


@bp.route('/lectures/<int:id>/update', methods=('GET','POST'))
@decorators.permission_professor
def lectures_update(id):
    """ View for updating Lectures """
    lecture = models.Lecture.query.filter_by(id=id).first()

    form = forms.formula_update(
                    table='lecture',
                    id=id,
                    week=('Integer',lecture.week),
                    Zahl=('Integer',lecture.Zahl),
                    day=('String',lecture.day),
                    title=('String',lecture.title),
                    summary=('TextArea',lecture.summary),
                    file_lecture=('File',None) )

    if form.validate_on_submit():
        filename = uploads.upload(form.file_lecture.data, 'lectures')
        lecture.update(
            id=form.Zahl.data,
            Zahl=form.Zahl.data,
            week=form.week.data,
            day=form.day.data,
            title=form.title.data,
            summary=form.summary.data,
            file_lecture=filename )

        flash(f"Lecture {form.Zahl.data} successfully updated")
        return redirect(url_for('lectures.lectures_index'))

    else:
        form.outtakes()

    return render_template('lectures/update.html', lecture=lecture, form=form)
                                                                ### END Lectures: Update


@bp.route('/lectures/<int:id>/delete', methods=('POST',))
@decorators.permission_professor
def lectures_delete(id):
    """ View for deleting Lectures """
    lecture = models.Lecture.query.filter_by(id=id).first()
    lecture.delete()

    flash(f"Lecture {id} successfully deleted")
    return redirect(url_for('lectures.lectures_index'))
                                                                ### END Lectures: Delete

main/templates/lectures/create.html
{% extends 'base.html' %}


{% block header %}
    <h1>{% block title %}New Lecture{% endblock %}</h1>
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {{ form.csrf_token() }}

        {% for field in form if (field.name != 'csrf_token') and (field.name != 'submit') %}
            {% if field.name == 'Zahl' %}
                {{ field.label(text='Lecture No.') }}
                {{ field }}
            {% elif field.name == 'day' %}
                {{ field.label(text='Date') }}
                {{ field }}
            {% elif field.name == 'file_lecture' %}
                {{ field.label(text='File') }}
                {{ field }}
            {% else %}
                {{ field.label }}
                {{ field }}
            {% endif %}
        {% endfor %}

        <hr>

        {{ form.submit() }}
        <a><button type="button" onClick = "this.form.reset()">Reset</button></a>
        <hr><hr>
        <a href="{{ url_for('lectures.lectures_index') }}"><button type="button">Back to Lectures</button></a>
    </form>
{% endblock %}

main/templates/lectures/lectures.html
{% extends 'base.html' %}

{% block header %}
	<h1>{% block title %}Lectures{% endblock %}</h1>
	{% if g.user['role_id'] == 4 %}
		<a class="action" href="{{ url_for('lectures.lectures_create') }}">New Lecture</a>
	{% endif %}
{% endblock %}

{% block content %}
	{% for wk in range(1, M+1) %}
	  	{% for lecture in lectures %}
			{% if lecture['week'] == wk %}
				<article class="post">
					<header>
						<div style="position: relative;">
							<h1><span class="BCE">Lecture {{ lecture['id'] }}: <a href="/gg">{{ lecture['title'] }}</a><span class="CE">{{ lecture['summary'] }}</span></span></h1>
							<div class="about">{{ lecture['day'] }}</div>
						</div>
						{% if g.user['role_id'] == 4 %}
							<a class="action" href="{{ url_for('lectures.lectures_update', id=lecture['id'] ) }}">Edit</a>
						{% endif %}
					</header>
				</article>
			{% endif %}
			{% if lecture['week'] > wk %} <!-- THIS TO GET CORRECT <hr> AFTER EACH WEEK -->
		 		{% break %}
			{% endif %}
	  	{% endfor %}
	 	<hr>
	{% endfor %}
{% endblock %}

main/templates/lectures/update.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Edit "{{ lecture['title'] }}"{% endblock %}</h1>
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {{ form.csrf_token() }}
        
        {% for field in form if (field.name != 'csrf_token') and (field.name != 'submit') %}
            {% if field.name == 'Zahl' %}
                {{ field.label(text='Assignment No.') }}
                {{ field }}
            {% elif field.name == 'day' %}
                {{ field.label(text='Date') }}
                {{ field }}
            {% elif field.name == 'file_lecture' %}
                {{ field.label(text='File') }}
                {{ field }}
            {% else %}
                {{ field.label }}
                {{ field }}
            {% endif %}
        {% endfor %}

        <hr>

        {{ form.submit() }}
        <a href="{{ url_for('lectures.lectures_index') }}"><button type="button">Back to Lectures</button></a>
    </form>
    <br>
    <form action="{{ url_for('lectures.lectures_delete', id=lecture['Zahl']) }}" method="post">
        <input class="danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
    </form>
{% endblock %}